/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AgentAssignmentCreateNestedManyWithoutClientsInput } from "./AgentAssignmentCreateNestedManyWithoutClientsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { AppointmentCreateNestedManyWithoutClientsInput } from "./AppointmentCreateNestedManyWithoutClientsInput";
import { EnumClientPreferredContactMethod } from "./EnumClientPreferredContactMethod";

@InputType()
class ClientCreateInput {
  @ApiProperty({
    required: false,
    type: () => AgentAssignmentCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => AgentAssignmentCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => AgentAssignmentCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  agentAssignments?: AgentAssignmentCreateNestedManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: () => AppointmentCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => AppointmentCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  appointments?: AppointmentCreateNestedManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fullName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumClientPreferredContactMethod,
  })
  @IsEnum(EnumClientPreferredContactMethod)
  @IsOptional()
  @Field(() => EnumClientPreferredContactMethod, {
    nullable: true,
  })
  preferredContactMethod?: "Option1" | null;
}

export { ClientCreateInput as ClientCreateInput };
